export const GET_QUESTIONS = 'GET_QUESTIONS';
export const SHOW_QUESTION = 'SHOW_QUESTION';
export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS';
export const ADD_QUESTION_FAIL = 'ADD_QUESTION_FAIL';
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
